---

- name: Create AWS resources
  connection: local
  gather_facts: false
  hosts: localhost
  roles:
    - ec2-asg

- name: configure instance application
  gather_facts: true
  hosts: asg_instances
  roles:
    - solana-validator
  tags:
    - application
