---

- name: test ssh connectivity
  ping:

- name: root activities
  block:
    - name: Set timezone to Europe/London
      community.general.timezone:
        name: Europe/London
        
    - name: Update distro
      apt:
        update_cache: true
        upgrade: true

    - name: install packages
      apt:
        name: "{{ item }}"
      loop: "{{ ubuntu_packages }}"
        
    - name: set tuned profile
      shell: tuned-adm profile throughput-performance

    - name: set sysctl settings
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
      with_dict: "{{ sysctl_config }}"

    - name: Add or modify hard nofile limits for wildcard domain
      community.general.pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: nofile
        value: "{{ sysctl_config['vm.max_map_count'] }}"
        
    - name: Create logrotate file
      copy:
        dest: /etc/logrotate.d/sol
        mode: '0644'
        content: |
          {{ solana_dir }}/logs/solana-validator.log {
            rotate 7
            daily
            missingok
            postrotate
              systemctl kill -s USR1 sol.service
            endscript
          }
    
    - name: Create sol.service
      copy:
        dest: /etc/systemd/system/sol.service
        mode: '0644'
        content: |
          [Unit]
          Description=Solana Validator
          After=network.target
          Wants=solana-sys-tuner.service
          StartLimitIntervalSec=0
          
          [Service]
          Type=simple
          Restart=always
          RestartSec=5
          User={{ default_user }}
          LimitNOFILE={{ sysctl_config['vm.max_map_count'] }}
          LogRateLimitIntervalSec=0
          Environment="PATH=/bin:/usr/bin:/home/{{ default_user }}/.local/share/solana/install/active_release/bin"
          ExecStart={{ solana_dir }}/bin/validator.sh
          
          [Install]
          WantedBy=multi-user.target

    - name: Create solana-sys-tuner.service
      copy:
        dest: /etc/systemd/system/solana-sys-tuner.service
        mode: '0644'
        content: |
          [Unit]
          Description=Solana Sys Tuner
          After=network.target
          StartLimitIntervalSec=0
          
          [Service]
          Type=simple
          Restart=always
          RestartSec=5
          User={{ default_user }}
          LimitNOFILE={{ sysctl_config['vm.max_map_count'] }}
          LogRateLimitIntervalSec=0
          Environment="PATH=/bin:/usr/bin:/home/{{ default_user }}/.local/share/solana/install/active_release/bin"
          ExecStart={{ solana_dir }}/bin/solana-sys-tuner.sh
          
          [Install]
          WantedBy=multi-user.target

    - name: Create custom solana-dev-setup
      copy:
        dest: /usr/local/bin/solana-dev-setup
        mode: '0775'
        content: |
          #!/bin/bash
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup component add rustfmt
          rustup update
          git clone --single-branch --branch master https://github.com/solana-labs/solana.git ~/solana && cd ~/solana
          cargo build --release &> ~/solana-build.log
          # ./run.sh &> ../solana-run.log &


    - name: Create custom solana-bench-dev
      copy:
        dest: /usr/local/bin/solana-bench-dev
        mode: '0775'
        content: |
          #!/bin/bash
          NDEBUG=1 ~/solana/multinode-demo/bench-tps.sh --entrypoint devnet.solana.com:8001 --faucet devnet.solana.com:9900 --duration 60 --tx_count 50

    - name: create solana directory
      file:
        path: "{{ solana_dir }}"
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory


  become: true



- name: create solana subdir
  file:
    path: "{{ solana_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - bin
    - logs
    - keys

- name: Create validator.sh
  copy:
    dest: "{{ solana_dir }}/bin/validator.sh"
    mode: '0740'
    content: |
      #!/bin/bash
      solana-validator \
        --identity     {{ solana_dir }}/keys/validator-keypair.json \
        --vote-account {{ solana_dir }}/keys/vote-account-keypair.json \
        --ledger       {{ solana_dir }}/validator-ledger \
        --rpc-port     8899 \
        --entrypoint   devnet.solana.com:8001 \
        --limit-ledger-size \
        --log          {{ solana_dir }}/logs/solana-validator.log
      EOF

- name: Create solana-sys-tuner.sh
  copy:
    dest: "{{ solana_dir }}/bin/solana-sys-tuner.sh"
    mode: '0740'
    content: |
      #!/bin/bash
      sudo /home/{{ default_user }}/.local/share/solana/install/active_release/bin/solana-sys-tuner \
           --user {{ default_user }} \
           &> {{ solana_dir }}/logs/sys-tuner.log

- name: get solana installer
  get_url:
    url: https://release.solana.com/stable/solana-install-init-x86_64-unknown-linux-gnu
    dest: "{{ solana_dir }}/bin/solana-install-init"
    mode: '0774'

# - name: get solana release
#   get_uri:
#     url: https://github.com/solana-labs/solana/releases/download/v1.4.19/solana-release-x86_64-unknown-linux-gnu.tar.bz2
#     dest: ~/solana-release-x86_64-unknown-linux-gnu.tar.bz2
#     mode: '0664'

- name: install solana client
  shell: 
    executable: /bin/bash
    chdir: "{{ solana_dir }}"
    cmd: |
      source ~/.profile
      
      which solana || ./bin/solana-install-init stable


- name: record solana versions
  shell: 
    executable: /bin/bash
    chdir: "{{ solana_dir }}"
    cmd: |
      source ~/.profile
      
      solanapath=$(echo $PATH | cut -d: -f1)
      for file in $(find $solanapath -maxdepth 1 -type f); do $file -V; done &> logs/solana-versions.txt

- name: install solana validator
  shell:
    executable: /bin/bash
    chdir: "{{ solana_dir }}"
    cmd: |
      source ~/.profile
      
      # Environment
      echo Set Environment:
      solana config set --url {{ solana_environment_url }}
      
      # Validator Keygen - unique per solana user
      echo -n '{{ solana_validator_key.private }}' > keys/validator-keypair.json
      echo Get Validator Keypair Public Key:
      solana-keygen pubkey keys/validator-keypair.json > keys/validator-keypair.pubkey
      cat keys/validator-keypair.pubkey
      echo Set Validator Keypair:
      solana config set --keypair keys/validator-keypair.json
      
      # Setup Balance
      echo Airdrop:
      solana airdrop 5
      echo Balance:
      solana balance
      echo Balance Lamports:
      solana balance --lamports
      
      # Vote Account Keygen
      echo Gen Vote Account KeyPair:
      [ ! -f 'keys/vote-account-keypair.json' ] && solana-keygen new -o keys/vote-account-keypair.json --no-passphrase
      echo Get Vote Account Keypair Public Key:
      solana-keygen pubkey keys/vote-account-keypair.json > keys/vote-account-keypair.pubkey
      cat keys/vote-account-keypair.pubkey
      echo Set VoteAccount:
      solana create-vote-account keys/vote-account-keypair.json keys/validator-keypair.json
      
      # Start vanity keygen
      echo Starting Vanity KeyGen:
      #solana-keygen grind --starts-with cwhee1:2 &> logs/cloudwheel-vanity.log &



# - name: setup solana development environment
#   shell:
#     executable: /bin/bash
#     chdir: "{{ solana_dir }}"
#     cmd: |
#       source ~/.profile
      
#       # # Setup development env
#       # apt -y install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make && \
#       # su -l {{ default_user }} -c "
#       #   /usr/local/bin/solana-dev-setup
#       # ">logs/dev-setup.log &


- block:

    - name: Reload service logrotate
      systemd:
        name: logrotate.service
        enabled: true
        daemon_reload: true
        state: reloaded

    - name: Reload service solana-sys-tuner
      systemd:
        name: solana-sys-tuner.service
        enabled: true
        daemon_reload: true
        state: restarted

    - name: Reload service solana
      systemd:
        name: sol.service
        enabled: true
        daemon_reload: true
        state: started

  become: true

- name: diagnostic links
  shell: 
    executable: /bin/bash
    cmd: |
      source ~/.profile
      
      echo "https://metrics.solana.com:3000/d/monitor-edge/cluster-telemetry-edge?refresh=60s&orgId=2&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=devnet&var-hostid=$(cat {{ solana_dir }}/keys/validator-keypair.pubkey)" > links.txt

- name: List ssh endpoints
  debug: msg="ssh {{ default_user }}@{{ ansible_host | default("unknown") }}"

- name: retrieve pub validator-keypair
  slurp:
    src: "{{ solana_dir }}/keys/validator-keypair.pubkey"
  register: validator_key
- name: retrieve pub vote-account-keypair
  slurp:
    src: "{{ solana_dir }}/keys/vote-account-keypair.pubkey"
  register: voter_key
  
- set_fact:
    validator_pubkey: "{{ validator_key.content | b64decode | trim}}"
    voter_pubkey: "{{ voter_key.content | b64decode | trim }}"


- name: retrieve list of cluster nodes
  uri:
    url: http://devnet.solana.com
    method: POST
    return_content: yes
    status_code: 200
    body: '{"jsonrpc":"2.0","id":1, "method":"getClusterNodes"}'
    body_format: json
  register: result
  until: result.json.result | length > 0
  retries: 5
  delay: 2

- name: debug - validators
  debug: msg="{{ item }}"
  loop: "{{ result.json | community.general.json_query('result[*].pubkey') }}"
  loop_control:
    label: "{{ item }}"
  



- name: retrieve list of vote accounts
  uri:
    url: http://devnet.solana.com
    method: POST
    return_content: yes
    status_code: 200
    body: '{"jsonrpc":"2.0","id":1, "method":"getVoteAccounts"}'
    body_format: json
  register: result
  until: result.json.result | length > 0
  retries: 5
  delay: 2

- name: debug
  debug: msg="{{ result.json.result | to_nice_yaml }}"
  #debug: msg="{{ result.json.result | community.general.json_query('result[*].pubkey') | default([[]])| first }}"

- debug: msg="validator public key:{{ validator_pubkey }} voter public key:{{ voter_pubkey }}"
